# Generated by Django 4.1.7 on 2023-03-31 06:31

from django.db import migrations, models
import django.db.models.deletion
from menu.helper import init_menu


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование меню')),
            ],
            options={
                'verbose_name': 'Наименование меню',
                'verbose_name_plural': 'Наименование меню',
                'db_table': 'menu_menu_name',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Метка')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='menu.menu', verbose_name='submenu')),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuname', verbose_name='menu name')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.RunPython(init_menu)
    ]
